### ISSUE TITLE
Problem of line numbers

### ISSUE THREAD

**Issue by egamess** [sinelaw/fresh#552]
Hello,

I am testing the Fresh editor. I am using Debian 13.2, on a x86/x64 architecture. I have a problem with line numbers.
I am editing the following file. It is a CSV file:
[vgsales-new.csv](https://github.com/user-attachments/files/24375246/vgsales-new.csv)

I just navigate with &lt;DownArrow&gt; and &lt;UPArrow&gt;, and I loose the synchronization of numbers. Look at the screenshots below. Line 6 of the CSV file is reported as line 5 by Fresh.
<img width="823" height="376" alt="Image" src="https://github.com/user-attachments/assets/bb96b752-c5cb-4c40-971b-133b5f65861b" />

Here is another screenshot. Now, line 10 of the CSV file is reported as line 8 by Fresh.
<img width="823" height="379" alt="Image" src="https://github.com/user-attachments/assets/9ba1cd5f-7086-46e1-b54f-73e565d911f9" />

I tried other files, and line numbers were working fine with the other files. But I do not know what is hapening in this case.

Thank you for looking at that

**Comment by sinelaw** [comment]
Fixed in 233311c6f429dc4f2f30fad25135eaae6b4aa0bc

**Comment by egamess** [comment]
Thank you so much for working on that. I downloaded version fresh-editor_0.1.67-1_amd64.deb. I think it should be the corrected version, since its has been updated a few hours ago. I still have the problem. I use a terminal of size 24 lines by 80 columns. After the first &lt;PageDown&gt;, it is already desynchronized. If I use several &lt;PageUp&gt; and &lt;PageDown&gt;, the synchronization problem can be of many lines. From time to time, it will come back to synchronization. Also, the same problem with &lt;ArrowUp&gt; and &lt;ArrowDown&gt;

<img width="793" height="505" alt="Image" src="https://github.com/user-attachments/assets/171a7aa6-2804-47d9-9b40-9498090a8df6" />

Thank you for your effort
