### ISSUE TITLE
panic when changing tab arrow visiblity

### ISSUE THREAD

**Issue by sinelaw** [sinelaw/fresh#580]
> After the change settings to hide the tab arrow for `cpp` language, we got error like:
> ```
> thread 'main' (269796) panicked at src/view/ui/view_pipeline.rs:159:25:
> attempt to calculate the remainder with a divisor of zero
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ``` 

 _Originally posted by @Eplankton in [#364](https://github.com/sinelaw/fresh/issues/364#issuecomment-3701844732)_

**Comment by Eplankton** [comment]
And we also find that after the panic info, re-entering the `Settings` will cause the `cpp language configs` to be vanished (everything's gone!) and `Reset` button doesn't work.

**Comment by sinelaw** [comment]
To reproduce

```
# 1. Checkout master and build
git checkout master
cargo build --release

# 2. Create test file with tabs
echo -e '\tint main() {\n\t\treturn 0;\n\t}' > /tmp/test.cpp

# 3. Create config with tab_size = 0
mkdir -p ~/.config/fresh
cat > ~/.config/fresh/config.json << 'EOF'
{
  "editor": {
    "tab_size": 0
  }
}
EOF

# 4. run
cargo run -- /tmp/test.cpp
```

**Comment by sinelaw** [comment]
Panic issue is fixed in master, config system is also under refactor so maybe the other issue is fixed as well (see updated user guide in master about config system)

**Comment by sinelaw** [comment]
(FYI the new config system in master is still under development, so may be confusing)

**Comment by Eplankton** [comment]
> And we also find that after the panic info, re-entering the `Settings` will cause the `cpp language configs` to be vanished (everything's gone!) and `Reset` button doesn't work.

Sorry but it seems that this problem still remains exist, settings vanished just like:

<img width="990" height="1318" alt="Image" src="https://github.com/user-attachments/assets/977aa233-4217-4f02-8c91-f3f40ae8dd73" />
